=== anmole17/comp_science_IBAB/sem3/TEE_AnmolSingh_225HSBB004/AnmolSingh_225HSBB004/q6/q6.dtd
<!ELEMENT Animals (Predator, Prey, BigAnimal, SmallAnimal)>
<!ELEMENT Predator (Predator1, Predator2, Predator3, Predator4)>
<!ELEMENT Predator1 (Name, Country, LifeSpan, Food)>
<!ELEMENT Name (#PCDATA)>
<!ELEMENT Country (#PCDATA)>
<!ELEMENT LifeSpan (#PCDATA)>
<!ELEMENT Food (#PCDATA)>
<!ELEMENT Predator2 (Name, Country, LifeSpan, Food)>
<!ELEMENT Predator3 (Name, Country, LifeSpan, Food)>
<!ELEMENT Predator4 (Name, Country, LifeSpan, Food)>
<!ELEMENT Prey (Prey1, Prey2, Prey3, Prey4)>
<!ELEMENT Prey1 (Name, Country, LifeSpan, Food)>
<!ELEMENT Prey2 (Name, Country, LifeSpan, Food)>
<!ELEMENT Prey3 (Name, Country, LifeSpan, Food)>
<!ELEMENT Prey4 (Name, Country, LifeSpan, Food)>
<!ELEMENT BigAnimal (BigAnimal1, BigAnimal2, BigAnimal3, BigAnimal4)>
<!ELEMENT BigAnimal1 (Name, Country, LifeSpan, Food)>
<!ELEMENT BigAnimal2 (Name, Country, LifeSpan, Food)>
<!ELEMENT BigAnimal3 (Name, Country, LifeSpan, Food)>
<!ELEMENT BigAnimal4 (Name, Country, LifeSpan, Food)>
<!ELEMENT SmallAnimal (SmallAnimal1, SmallAnimal2, SmallAnimal3, SmallAnimal4)>
<!ELEMENT SmallAnimal1 (Name, Country, LifeSpan, Food)>
<!ELEMENT SmallAnimal2 (Name, Country, LifeSpan, Food)>
<!ELEMENT SmallAnimal3 (Name, Country, LifeSpan, Food)>
<!ELEMENT SmallAnimal4 (Name, Country, LifeSpan, Food)>

=== anmole17/comp_science_IBAB/sem3/TEE_AnmolSingh_225HSBB004/AnmolSingh_225HSBB004/q6/q6.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Animals SYSTEM "q6.dtd">
<Animals>
<Predator>
<Predator1>
<Name>Lion</Name>
<Country>India</Country>
<LifeSpan>15years</LifeSpan>
<Food>Carnivore</Food>
</Predator1>
<Predator2>
<Name>Cheeta</Name>
<Country>India</Country>
<LifeSpan>20years</LifeSpan>
<Food>Carnivore</Food>
</Predator2>
<Predator3>
<Name>Tiger</Name>
<Country>India</Country>
<LifeSpan>10years</LifeSpan>
<Food>Carnivore</Food>
</Predator3>
<Predator4>
<Name>Wolf</Name>
<Country>India</Country>
<LifeSpan>7years</LifeSpan>
<Food>Carnivore</Food>
</Predator4>
</Predator>
<Prey>
<Prey1>
<Name>Deer</Name>
<Country>India</Country>
<LifeSpan>10years</LifeSpan>
<Food>Herbivore</Food>
</Prey1>
<Prey2>
<Name>Rabbit</Name>
<Country>India</Country>
<LifeSpan>3years</LifeSpan>
<Food>Omnivore</Food>
</Prey2>
<Prey3>
<Name>Katla</Name>
<Country>India</Country>
<LifeSpan>2years</LifeSpan>
<Food>Omnivore</Food>
</Prey3>
<Prey4>
<Name>Giraffe</Name>
<Country>India</Country>
<LifeSpan>15years</LifeSpan>
<Food>Herbivore</Food>
</Prey4>
</Prey>
<BigAnimal>
<BigAnimal1>
<Name>Elephant</Name>
<Country>India</Country>
<LifeSpan>30years</LifeSpan>
<Food>Hearbivore</Food>
</BigAnimal1>
<BigAnimal2>
<Name>Hippopotamus</Name>
<Country>India</Country>
<LifeSpan>23 years</LifeSpan>
<Food>Omnivore</Food>
</BigAnimal2>
<BigAnimal3>
<Name>Giraffe</Name>
<Country>India</Country>
<LifeSpan>15years</LifeSpan>
<Food>Herbivore</Food>
</BigAnimal3>
<BigAnimal4>
<Name>Whale</Name>
<Country>India</Country>
<LifeSpan>40years</LifeSpan>
<Food>Omnivore</Food>
</BigAnimal4>
</BigAnimal>
<SmallAnimal>
<SmallAnimal1>
<Name>Rabbit</Name>
<Country>India</Country>
<LifeSpan>3years</LifeSpan>
<Food>Omnivore</Food>
</SmallAnimal1>
<SmallAnimal2>
<Name>Rat</Name>
<Country>India</Country>
<LifeSpan>1year</LifeSpan>
<Food>Omnivore</Food>
</SmallAnimal2>
<SmallAnimal3>
<Name>Cat</Name>
<Country>India</Country>
<LifeSpan>8years</LifeSpan>
<Food>Carnivore</Food>
</SmallAnimal3>
<SmallAnimal4>
<Name>Sparrow</Name>
<Country>India</Country>
<LifeSpan>5years</LifeSpan>
<Food>Omnivore</Food>
</SmallAnimal4>
</SmallAnimal>
</Animals>
