=== anmole17/comp_science_IBAB/sem3/Assignment15_27_10_23/assignment2.dtd
<!ELEMENT vehicles (car, cycle, bus)>
<!ELEMENT car (n_passenger, size, wheels, cost, safety, fuel)>
<!ELEMENT cycle (n_passenger, size, wheels, cost, safety, fuel)>
<!ELEMENT bus (n_passenger, size, wheels, cost, safety, fuel)>
<!ELEMENT n_passenger (#PCDATA)>
<!ELEMENT size (#PCDATA)>
<!ELEMENT wheels (#PCDATA)>
<!ELEMENT cost (#PCDATA)>
<!ELEMENT safety (#PCDATA)>
<!ELEMENT fuel (#PCDATA)>

=== anmole17/comp_science_IBAB/sem3/Assignment15_27_10_23/assignment2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE vehicles SYSTEM "assignment2.dtd">
<vehicles>
<car>
<n_passenger>4</n_passenger>
<size>medium</size>
<wheels>4</wheels>
<cost>600000</cost>
<safety>good</safety>
<fuel>petrol, CNG, diesel</fuel>
</car>
<cycle>
<n_passenger>1</n_passenger>
<size>small</size>
<wheels>2</wheels>
<cost>5000</cost>
<safety>bad</safety>
<fuel>No fuel</fuel>
</cycle>
<bus>
<n_passenger>60</n_passenger>
<size>large</size>
<wheels>6</wheels>
<cost>15L</cost>
<safety>medium</safety>
<fuel>petrol, CNG, diesel</fuel>
</bus>
</vehicles>
